### ISSUE TITLE
Api question

### ISSUE THREAD

**Issue by Freyr666** [paurkedal/ocaml-caqti#14]
I'm trying to integrate caqti into my project and I have some questions about caqti api. Why functions like `collect`, `exec`, `find` etc are duplicated in both `CONNECTION` and `Caqti_request`?

Would it be possible to have something like this:

    let collect = Caqti_request.collect Caqti_type.int Caqti_type.string "REQUEST"
    val collect : (int, string list) request

    let find = Caqti_request.find Caqti_type.int Caqti_type.string "REQUEST"
    val find : (int, string option) request

and then just
   
    Conn.exec collect 42
    val string option Lwt.t

    Conn.exec find 42
    val string list Lwt.t

?

For example I could call `Conn.collect_list (Caqti_request.find ... )...` and it would work fine if there are entries, but fail if no entries were found.

**Comment by paurkedal** [comment]
This would be possible, but I think such a solution would have some quirks:

Note that `Caqti_type` allows rows to be decoded as options, where `None` means all-`NULL`.  An option in the return type of your version of `request` would therefore indicate either a search which may return zero or one row or a search which may return one row decoded by `Caqti_type.option`.  So, it would work, but I think it is less informative what's happening.

On the other hand, a `list` typed result can only be produced by multiple rows, at least with the Caqti base types which don't support SQL extensions like arrays.  So, a `list` result would be unambiguous at the moment.  However it's not given that we want to extract the result as a manifest list, and I consider `fold`, `fold_s`, and `iter_s` to be the primitives for extracting multi-row results.  It would still work to use `list` as a marker, in an earlier sketch I experimented with a dedicated type constructor instead, but the bottom line is I though it was tidier to use a third parameter of the request type for the purpose.

I also have in mind that we may want to build higher-level APIs on top of Caqti and I'm betting on explicit row multiplicity as easier to work with, but I may be wrong.

There is one feature or maybe misfeature related to this.  Using a polymorphic variant allows e.g. executing a unique query with either `find`, `find_opt`, or the iterators.

**Comment by Freyr666** [comment]
>An option in the return type of your version of request would therefore indicate either a search which may return zero or one row or a search which may return one row decoded by Caqti_type.option

I think it's pretty consistent since it's a sort of mapping of sql types to the OCaml realm, but option is not the thing which is bothering me.

What really bothers me is the scattering of the query logic, i.e. I need 1) create a proper query 2) make a proper call, which seems very redundant. Imho a query should carry enough information about types and logic. It's fine to have functions like `fold`, but `exec`, `collect_list` and `find` looks very excessive.

And it also makes the creation of a good api a little bit more tedious since there should be some query logic on a request building side and on a call side. To write something like this:

    val model : type (req, resp). (req, resp) query -> req -> resp

I have to introduce some intermediate type

    type (_, _) query = List (a,b) request -> (a,b list) query | Exec (a,unit) request -> (a,unit) query

Not a big deal, but seems unnecessary

**Comment by paurkedal** [comment]
> > An option in the return type of your version of request would therefore indicate either a search which may return zero or one row or a search which may return one row decoded by Caqti_type.option
>
> I think it's pretty consistent since it's a sort of mapping of sql types into the OCaml realm, but option is not the thing which is bothering me.

It would be if Caqti provided multi-row decoding in the request part, but currently processing of rows is delegated to the result handler.  `fold` is the only retriever needed, but due to the multiplicity parameter, it is possible to provide some safe convenience functions <= 1 row cases.

> What really bothers me is the scattering of the query logic, i.e. I need to 1) create a proper query and then to 2) make a proper call, which seems very redundant. Imho a query should carry enough information about types and the query logic. It's fine to have functions like fold (however fold could also be a request rather than a function in the CONNECTION), but `exec`, `collect_list` and `find` look very excessive.

The division is between constructing an SQL query and declaring the relevant, and only the relevant, information and implementing the extraction of rows.  The latter is not really related to the query, except that the query may provide some constraints.  One could go even further than you suggest, and merge the request constructors with suitable retrievers, and putting everything in the connection API.  A technical reason for keeping them separate is to support prepared queries.  I also think it's natural in common cases to define the queries on the toplevel, though a notable exception is generated queries.

Note that `collect_list` is just a convenience for `fold List.cons req []` followed by reversal.  I don't consider `list` to belong to the core interface since later version may support big datasets which might not fit in memory, at least where the driver supports it. (Like the single-row mode of PG.)

> And it also makes the creation of a good api a little bit more tedious [...]

Yes, but that dispatch needs to be done either in Caqti or the higher level API, and I prefer to keep the semantics of Caqti close to the client libraries for leanness and ease of maintenance and maybe to avoid making too many decisions on behalf of any higher level solution.

> Not a big deal, but seems unnecessary, and of course I could accidentally call the `find` request with the `collect_list` function, which leads to a rather unexpected result.

Calling `collect_list` on the response from a `find`-query would return a list containing the decoded value of the returned row.  That is expected, isn't it?  In fact `find` (and by implication `collect_list`) works on any request.

**Comment by Freyr666** [comment]
>That is expected, isn't it? In fact find (and by implication collect_list) works on any request.

Nope, if there are no rows found it returns a failed thread instead of an empty list.

**Comment by paurkedal** [comment]
> Nope, if there are no rows found it returns a failed thread instead of an empty list.

The `find` constructor must only be used for queries which are guaranteed to return a single row.  If that condition is not fulfilled, the result should be `` Error `Response_rejected``, indicating a bug in client code.

**Comment by paurkedal** [comment]
I made some clarification in the `Caqti_connection_sig` API docs in the last commit which hopefully also will make the design more clear.  I will close this with that, as I don't want to add multi-row decoding specifications into request objects.
