### ISSUE TITLE
PostgreSQL custom types

### ISSUE THREAD

**Issue by pdonadeo** [paurkedal/ocaml-caqti#16]
Is it possible so extend the PostgreSQL driver to use custom types? I'm particularly interested in `array` types and `jsonb`

https://www.postgresql.org/docs/current/static/arrays.html
https://www.postgresql.org/docs/current/static/datatype-json.html

**Comment by paurkedal** [comment]
For JSON, just pass the values as strings.  This is how it's passed anyway by the PostgreSQL driver, and when using a database which don't support JSON natively, one would typically use a `TEXT` field anyway.

Arrays can also be passed as stings, using the notation of the page you cite.  This is because libpq uses strings to pass all kind of values, and since arrays are PG specific, you can only use them with this driver anyway.

**Comment by pdonadeo** [comment]
@paurkedal thanks for this workaround, I will use a string. I meant a more general question: is it possible to extend the basic types in a specific driver without modifying the library? The hint is in [`caqti_type.mli`](https://github.com/paurkedal/ocaml-caqti/blob/master/lib/caqti_type.mli#L24):
```ocaml
type 'a field = ..
(** An extensible type describing primitive SQL types and types which can be
    converted to and from such types.  When adding a new constructor, register
    the coding with {!Field.define_coding} if possible.  Otherwise, the type
    will only work with drivers which handle it themselves.  The shipped drivers
    only handle the constructors listed here. *)
```
Obviously I must give up DB portability, but this is not a problem at all in my current project.

**Comment by pdonadeo** [comment]
Found an example in `caqti_type_calendar.ml`.

**Comment by paurkedal** [comment]
Good you found it.  Yes, this works as long as there is a compatible base type, and in case of PostgreSQL that will be the case, since the non-standard types have string representations.
