### ISSUE TITLE
Caqti in a plain Unix environment

### ISSUE THREAD

**Issue by pdonadeo** [paurkedal/ocaml-caqti#18]
This is not an issue, more a feature request.
I'm using Cacti in 2/3 production projects and in that context I'm also using Async to handle concurrency and everything runs smoothly.

Now I have a simple system program (it could actually be written in BASH but... why should I shot myself in a foot?) interacting with PostgreSQL. In that context I don't need Lwt/Async because it's a very simple and sequential program making a couple of SELECT, some computations and finally some UPDATEs.

Is it possible to use Caqti in such environment? I don't need pooling or any other advanced feature: the old plain Unix module is more than enough.

**Comment by paurkedal** [comment]
I have considered writing a blocking Unix instance of the API, so yes that is very possible and a good idea given the need.

I think I understand your use case, I'm also using Caqti for ad-hoc programs to do specific tasks against a database.  However, I tend to use Lwt even simple system scripting tasks, since I think it provides a better Unix and IO library than plain OCaml, and since I like the way monads makes effects explicit.  Thus, I haven't had a motivation  to write the blocking Unix module yet.

**Comment by pdonadeo** [comment]
Thanks @paurkedal. Since I'm interested in this module, what do you think if I develop such module and submit a pull request?

If you agree I'll only need some help about where to find relevant interfaces to implement and some code review, of course, to keep the codebase homogeneous.

**Comment by paurkedal** [comment]
A unix-based blocking API is now implemented in the master branch in the library `caqti.blocking` of the main package.  You can test by pinning `caqti*` packages to the `--dev-repo`.

**Comment by pdonadeo** [comment]
Thanks! I'll try it ASAP!
