### ISSUE TITLE
Assert_failure when executing many queries with a pool

### ISSUE THREAD

**Issue by roddyyaga** [paurkedal/ocaml-caqti#34]
I'm getting
```
Exception: Assert_failure ("lib/caqti_connection.ml", 26, 4).
Raised at file "lib/caqti_connection.ml", line 26, characters 4-24
```
when I try to execute lots of queries using a pool. Is this expected?

My code is something like this:
```ocaml
let do_many dbh =
    let results = List.map ~f:(fun x -> do_some_query x dbh) xs in
   sequence results
```
where `sequence` is
```ocaml
let sequence xs =
  let open Lwt_result.Infix in
  List.fold ~init:(return [])
    ~f:(fun accum x ->
      accum >>= fun accum ->
      x >|= fun x -> x :: accum)
    xs
```

And then I do `Caqti_lwt.Pool.use do_many a_pool`.

This is using Postgres.

**Comment by roddyyaga** [comment]
I fixed this by replacing `List.map` with `Lwt_list.map` and `sequence` with `Result.all`, but would still be curious to know what was happening.

**Comment by paurkedal** [comment]
Constructing Lwt threads with `List.map` means they will run in parallel, since Lwt has eager execution semantics. Caqti connection handles can only accept a single request at the time, since it (including the underlying connection handle) is stateful. To run requests in parallel, you can use a dedicated connection handle per thread, which is where connection pooling come to good use.

**Comment by roddyyaga** [comment]
Oh right, I hadn't considered that `Caqti_lwt.Pool.use do_many a_pool` would get one connection from the pool and then use it for all the subqueries. Given that it makes perfect sense, thanks.
