### ISSUE TITLE
support for pg_notify

### ISSUE THREAD

**Issue by tcoopman** [paurkedal/ocaml-caqti#39]
I'm not sure if this is something you want to implement, but supporting `pg_notify` would be really nice.

An example of how it's implemented in `postgresql-ocaml` can be found here: https://github.com/mmottl/postgresql-ocaml/blob/5ed13a60d804953f1f3356271ffc20d347134c9a/examples/prompt.ml#L51

**Comment by paurkedal** [comment]
It looks like a nice PostgreSQL feature, though I have some reservation about adding support for it to Caqti.  First, I don't think there is an equivalent for MariaDB or SQLite3.  Second, notification handling doesn't seem to be a good fit for connection pools, since it is essential to maintain the listening connection in an open state.

Combining those two points, I don't think Caqti support would add much, as one might as well open a dedicated connection using the postgresql-ocaml library, maybe turning the events into a react event which different parts of the application could use, while using a Caqti pool for sending regular requests.

**Comment by tcoopman** [comment]
Ok, thought as much but good to get confirmation!

**Comment by cemerick** [comment]
> Second, notification handling doesn't seem to be a good fit for connection pools, since it is essential to maintain the listening connection in an open state.

Having just completed implementing a reasonably general-purpose notification mechanism on top of postgresql-ocaml, I'd like to offer a counterpoint:

While it's true that `LISTEN` is a stateful thing that needs to be tied to a single connection, in a "real world" context, the inevitable end state of a LISTEN implementation requires all kinds of reconnection logic that would be perfectly satisfied by a connection pool of size 1.
