### ISSUE TITLE
(Some kind of) offline SQL backend

### ISSUE THREAD

**Issue by pw374** [paurkedal/ocaml-caqti#52]
Hi, I'd be interested in using an "offline" backend. (I don't know if there's already a name for that.)

It would simply consist in printing all the SQL commands instead of passing them to the DB engine.

Please could you tell me if there's already a way to do it, or where to look if I were to implement it?

**Comment by paurkedal** [comment]
Using `sqlite3::memory:` would be as offline as it gets with the current distribution, no network or disk backing.  But one could also write a "null" driver which accepts any query and never returns a result, or an "echo" driver which accepts any query and returns a single row containing the same query.  However, if this is for testing and debugging, isn't a memory-backed database preferred?

It might be useful to add some debug-level logging of SQL statements, though. I haven't missed it much since caqti errors includes the query, but there might be cases where one wants to inspect statements which are not failing.

I haven't documented how to write drivers, so the only option here is to look at one of the existing ones under lib-driver. I should also note that I don't guarantee backwards compatibility between minor version for the driver API at the moment, though I would reconsider that if needed.

**Comment by pw374** [comment]
Thank you for you reply :) 

The use case for me is the following:
- I have a project that makes as many SQL requests as it possibly can for a few days; then it just a few hundreds/thousands per minute;
  - (more precisely, I index the tezos blockchain using PG)
- because of the complexity of the project, I find it much easier to look at the queries actually being made than to look anywhere else when it comes to finding useless SQL transactions.
- Yesterday, I set up PG to log all queries, the format is quite bad but it's better than nothing. So, having that "offline" backend is less useful than before I did that.
  - In that case, it allowed me to spot (by using some `sed` and `sort`) some queries that were done multiple times (with same data, therefore no effect on the DB other than uselessly consuming resources).

- However I'm still interested in generating a huge SQL file with all the requests instead of executing them. That way, it'd be easier to get a "(poor) dump" of the SQL data since I could then easily do something like `run-project | tee db.sql | psql`.
  - I would —of course— **not** prefer this over the normal way! It would be horrible to handle errors coming out of such a set-up. But the point is, when it's running this way, there are presumably no "SQL errors".
  - Such backend would also allow better debugging (not of SQL queries), some different kind of testing, and some optimisations.


Hopefully I'll find the time to look into `lib-driver`. :) I'll let you know if I do some hacking in there.

I'm gonna close this issue for now so it doesn't uselessly add to the list. (But if you feel it's more interesting than you initially thought, of course, it'd be great to have this re-opened :p)

**Comment by paurkedal** [comment]
It is probably not so common that the application can proceed without a positive response. I could see a more general use for logging the SQL statements (or transactions) parallel to talking to a database. Wouldn't that also suffice for what you are trying to accomplish?

If I implement something, I would send the SQL queries to the Logs library, which would mean you'd need to dig it out of a log file or set up a custom reporter.

**Comment by pw374** [comment]
When running in "normal mode", the process exits in case of any error.

Anything allowing me to get a better understanding of the computations being done in my project would be very welcome :)
That being said, I'd also be very interested in knowing how fast the whole thing would be if PG was "infinitely fast" (meaning as fast as outputting the queries to `/dev/null`). For that, I guess I'd need to have a specific driver that does "almost nothing", which could be "simplified" as "printing the SQL queries to `stdout`" (which could then be redirected to `/dev/null`).

As I sped up the SQL part a little bit yesterday, the load on the tezos node increased significantly! (and the load on PG decreased a bit)
