### ISSUE TITLE
How to set default charset?

### ISSUE THREAD

**Issue by Nymphium** [paurkedal/ocaml-caqti#66]
For example, [ocaml-mysql](https://github.com/ygrek/ocaml-mysql) can connect to a database with specific charset optionally.
```ocaml
Mysql.(connect ~options:[SET_CHARSET_NAME "utf8mb4"])
```
Does caqti have such a option?

**Comment by paurkedal** [comment]
There is no way to set the character encoding it via the Caqti API, as I have assumed UTF-8 as the only relevant option today, but I was not aware of the BMP limitation of the default encoding for MariaDB. However, I can see that `utf8me3` which now is aliased as `utf8` is deprecated, so how about if we override it already now in the MariaDB driver?

**Comment by Nymphium** [comment]
Ok, I'll create the modified driver. Thank you!

**Comment by paurkedal** [comment]
I meant that I will apply this is the shipped driver, if you agree this is a reasonable solution. Sorry for the confusion.

I am pondering whether this can could cause issues for existing code, but as I understand it we would be strictly extending which strings can be transforred, and since the extra characters into OCaml UTF-8 encoded strings, we won't need any breaking changes. But please let me know if you can thing of something I'm missing.

**Comment by paurkedal** [comment]
Fixed by 2c6a05730114687bc096fbc304e0124df69391a1. I sent a PR for an OPAM release.
