### ISSUE TITLE
Returning a list of row result

### ISSUE THREAD

**Issue by bobbypriambodo** [paurkedal/ocaml-caqti#8]
Hi, thanks for this library! I've been playing with it and I'm loving the types. I managed to get basic queries running. However it would seem to me that `Caqti_lwt.CONNECTION` does not directly provide a way to return a list of results? Here's what I have so far:

```ocaml
module Q = struct
  let get_all_todos =
    Caqti_request.collect
      Caqti_type.unit
      Caqti_type.(tup2 int string)
      "SELECT id, content FROM todos"
end

let get_all_internal (module Db : Caqti_lwt.CONNECTION) =
  Db.fold Q.get_all_todos (fun (id, content) acc ->
    { id = id; content = content } :: acc
  ) () []
```

See that in `get_all_internal` I use `Db.fold` to construct a list of todos. However, the way I append it means that the final result I get is reversed. Of course I can reverse it back before returning it to the caller, but I'm curious if there's a better way to do this.

Perhaps there should be a `Db.collect` function or am I missing something?

**Comment by paurkedal** [comment]
That's how I use it as well, when I need a list, though sometimes I don't need to modify the result, and use `Fb.fold request List.cons arg []`. As you note, the result will be reversed, which can be countered either with by using the opposite `ORDER BY` or by reversing the list. There is no way of building the list in the returned order without buffering it first, so adjusting the query is the most efficient.

The main reason I didn't include a function to return a list is that it's relatively easy to extract it from `fold` with allows mapping it in the same operation, and sometime one wants a `Set.S`, `Map.S` or other container instead.  But, I tend to agree that extracting lists may be important enough to add a convenience function, or maybe two, one returning the reversed result for efficiency.

The name `collect` seems appropriate, except it was meant as a common term to match any collection processing functions in the `Db` API, so instead of giving lists a special status by choosing the same name, maybe `list` and `rev_list`, `to_list` and `to_list_rev`, or `rows` and `rev_rows`.

**Comment by bobbypriambodo** [comment]
Yes, I think `fold` and `iter` is good for the foundation, but I agree that convenience functions for lists would be useful. I like `list` and `rev_list`, with `list` docs noting the extra complexity, although I believe it would still be O(n) for both, and I'm not sure if returning a large number of rows is a good practice anyway. `ORDER BY` is also a neat workaround.

**Comment by paurkedal** [comment]
Yes, it's all O(n), with a constant which is probably dominated by the transfer of the results anyway, if not by the query itself on the DB side.

**Comment by paurkedal** [comment]
I decided to name the functions `collect_list` and `collect_list_rev`, as I wasn't quite satisfied with a bare noun here.  We can still rename before the next release if we come up with better names.

**Comment by bobbypriambodo** [comment]
Tried it on master and works as expected. This would be neat for when using we're using custom types. Thank you! Really digging this library so far, I really hope it can be the de facto solution for dealing with databases in OCaml.

**Comment by paurkedal** [comment]
Thanks for the positive feedback. I have been working on this in isolation for some time, so it's nice to know it makes sense to other people, as well.

**Comment by paurkedal** [comment]
I noticed in `List`, it's called `rev_map`, so I renamed `collect_list_rev` to `rev_collect_list`.
